#%RAML 1.0 DataType
type: object
description: Create Customer Response
properties:
  clientKey: string
  firstName: string
  middleName: string
  lastName: string
  birthDate: date-only
  height: number
  weight: number
  billingAddress: string