#%RAML 1.0 NamedExample
clientKey: "000000001"
firstName: "Kossivi"
middleName: "Selom"
lastName: "Afeli"
birthDate: "1989-12-17"
height: 1.83
weight: 83
billingAddress: "Rue des Ecoliers Cyber City Ebene 7795 230"