#%RAML 1.0
title: customerMngmt
version: 1.0
mediaType: 
- application/json


types:
  createCustomerRequest: !include types/create-customer-request.raml
  
  bulkCustomerResponse: !include types/bulkCustomerObject.raml




/customer:
  post:
    body:
      application/json:
        type: createCustomerRequest
        example:
          !include examples/create-customer-request.raml
    responses:
      201:
        body:
          text/plain:
            example:
              "Created"
  get:
    responses:
          200:
            body:
              application/json:
                type: bulkCustomerResponse
                example:
                  !include examples/bulkCustomerObject.raml
  delete:
    queryParameters:
      clientKey: 
        type: string
        required: true

    responses:
      200:
        body:
          text/plain:
            example:
              "Deleted!"
        